CREATE TYPE "FulfilmentType" AS ENUM ('PICKUP','DELIVERY','DINE_IN');
CREATE TYPE "OnlineOrderStatus" AS ENUM ('DRAFT','PAYMENT_PENDING','PENDING_ACCEPTANCE','ACCEPTED','PREPARING','READY','OUT_FOR_DELIVERY','COMPLETED','DELIVERED','REJECTED','CANCELLED','PAYMENT_FAILED','REFUNDED');
CREATE TYPE "OrderingAcceptanceMode" AS ENUM ('AUTOMATIC','MANUAL');
ALTER TYPE "OrderSource" ADD VALUE IF NOT EXISTS 'WEB_PICKUP';
ALTER TYPE "OrderSource" ADD VALUE IF NOT EXISTS 'WEB_DELIVERY';
ALTER TYPE "OrderSource" ADD VALUE IF NOT EXISTS 'QR_DINE_IN';

ALTER TABLE "Order" ADD COLUMN "publicOrderNumber" TEXT, ADD COLUMN "trackingToken" TEXT, ADD COLUMN "fulfilmentType" "FulfilmentType", ADD COLUMN "onlineStatus" "OnlineOrderStatus", ADD COLUMN "customerName" TEXT, ADD COLUMN "customerEmail" TEXT, ADD COLUMN "customerPhone" TEXT, ADD COLUMN "scheduledFor" TIMESTAMP(3), ADD COLUMN "estimatedReadyAt" TIMESTAMP(3), ADD COLUMN "acceptedAt" TIMESTAMP(3), ADD COLUMN "rejectedAt" TIMESTAMP(3), ADD COLUMN "rejectionReason" TEXT, ADD COLUMN "readyAt" TIMESTAMP(3), ADD COLUMN "completedAt" TIMESTAMP(3), ADD COLUMN "discount" DECIMAL(10,2) NOT NULL DEFAULT 0, ADD COLUMN "serviceCharge" DECIMAL(10,2) NOT NULL DEFAULT 0, ADD COLUMN "deliveryFee" DECIMAL(10,2) NOT NULL DEFAULT 0, ADD COLUMN "tip" DECIMAL(10,2) NOT NULL DEFAULT 0, ADD COLUMN "paymentStatus" TEXT NOT NULL DEFAULT 'UNPAID', ADD COLUMN "stripePaymentIntentId" TEXT, ADD COLUMN "idempotencyKey" TEXT;
CREATE UNIQUE INDEX "Order_publicOrderNumber_key" ON "Order"("publicOrderNumber");
CREATE UNIQUE INDEX "Order_trackingToken_key" ON "Order"("trackingToken");
CREATE UNIQUE INDEX "Order_idempotencyKey_key" ON "Order"("idempotencyKey");
CREATE INDEX "Order_onlineStatus_scheduledFor_idx" ON "Order"("onlineStatus","scheduledFor");
CREATE INDEX "Order_createdAt_fulfilmentType_idx" ON "Order"("createdAt","fulfilmentType");

CREATE TABLE "OnlineOrderingConfig" ("id" TEXT PRIMARY KEY, "locationId" TEXT NOT NULL UNIQUE, "isEnabled" BOOLEAN NOT NULL DEFAULT true, "isPaused" BOOLEAN NOT NULL DEFAULT false, "pauseReason" TEXT, "acceptanceMode" "OrderingAcceptanceMode" NOT NULL DEFAULT 'MANUAL', "pickupEnabled" BOOLEAN NOT NULL DEFAULT true, "deliveryEnabled" BOOLEAN NOT NULL DEFAULT true, "dineInEnabled" BOOLEAN NOT NULL DEFAULT true, "scheduledOrdersEnabled" BOOLEAN NOT NULL DEFAULT true, "pickupLeadMinutes" INTEGER NOT NULL DEFAULT 20, "deliveryLeadMinutes" INTEGER NOT NULL DEFAULT 45, "minimumPickupAmount" DECIMAL(10,2) NOT NULL DEFAULT 0, "minimumDeliveryAmount" DECIMAL(10,2) NOT NULL DEFAULT 0, "deliveryRadiusKm" DOUBLE PRECISION NOT NULL DEFAULT 8, "deliveryFee" DECIMAL(10,2) NOT NULL DEFAULT 0, "freeDeliveryThreshold" DECIMAL(10,2), "serviceChargePercent" DECIMAL(5,2) NOT NULL DEFAULT 0, "maximumOrdersPerSlot" INTEGER NOT NULL DEFAULT 10, "slotDurationMinutes" INTEGER NOT NULL DEFAULT 15, "customerInstructions" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "OnlineOrderingConfig_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "Location"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "OnlineOrderingHours" ("id" TEXT PRIMARY KEY, "configId" TEXT NOT NULL, "dayOfWeek" INTEGER NOT NULL, "orderType" "FulfilmentType" NOT NULL, "openTime" TEXT NOT NULL, "closeTime" TEXT NOT NULL, "isClosed" BOOLEAN NOT NULL DEFAULT false, CONSTRAINT "OnlineOrderingHours_configId_fkey" FOREIGN KEY ("configId") REFERENCES "OnlineOrderingConfig"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "OnlineOrderingHours_configId_dayOfWeek_orderType_key" ON "OnlineOrderingHours"("configId","dayOfWeek","orderType");
CREATE TABLE "OrderDeliveryAddress" ("id" TEXT PRIMARY KEY, "orderId" TEXT NOT NULL UNIQUE, "locationId" TEXT NOT NULL, "addressLine1" TEXT NOT NULL, "addressLine2" TEXT, "city" TEXT NOT NULL, "state" TEXT NOT NULL, "postalCode" TEXT NOT NULL, "latitude" DOUBLE PRECISION, "longitude" DOUBLE PRECISION, "distanceKm" DOUBLE PRECISION, "instructions" TEXT, CONSTRAINT "OrderDeliveryAddress_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "OrderDeliveryAddress_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "Location"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
