import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { rateLimit, rateLimitResponse } from '@/lib/rate-limit'
import bcrypt from 'bcryptjs'
import { z } from 'zod'

const ownerSignupSchema = z.object({
  signupType:      z.literal('OWNER').default('OWNER'),
    restaurantName:  z.string().min(2).max(100),
      ownerName:       z.string().min(2).max(100),
        email:           z.string().email(),
          password:        z.string().min(12).max(100),
            locationName:    z.string().min(1).max(100).default('Main Outlet'),
              phone:           z.string().optional().nullable(),
                managerName:     z.string().optional(),
                  managerEmail:    z.string().email().optional(),
                    managerPassword: z.string().min(12).optional(),
                      serverName:      z.string().optional(),
                        serverEmail:     z.string().email().optional(),
                          serverPassword:  z.string().min(12).optional(),
                            kitchenName:     z.string().optional(),
                              kitchenEmail:    z.string().email().optional(),
                                kitchenPassword: z.string().min(12).optional(),
                                })

                                // ─── POST /api/auth/signup ──────────────────────────────────────────────────
                                // Public registration is limited to new restaurant owners. Existing owners and
                                // managers create staff through the authenticated /api/users endpoint.
                                export async function POST(req: NextRequest) {
                                  try {
                                      const ip = req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() || req.headers.get('x-real-ip') || 'unknown-ip'
                                          const rl = await rateLimit(`auth:signup:${ip}`, 5, 600)
                                              if (!rl.allowed) {
                                                    return rateLimitResponse(rl.retryAfterSec)
                                                        }

                                                            const body = await req.json()
                                                                const signupType = body.signupType === 'STAFF' ? 'STAFF' : 'OWNER'

                                                                    // ── Staff Registration (Manager, Server, Kitchen) ────────────────────────
                                                                        if (signupType === 'STAFF') {
                                                                              return NextResponse.json(
                                                                                      {
                                                                                                error: 'Staff self-registration is disabled. Ask an owner or manager to create your account.',
                                                                                                        },
                                                                                                                { status: 403 }
                                                                                                                      )
                                                                                                                          }

                                                                                                                              // ── Owner Registration (Tenant & Location Setup) ─────────────────────────
                                                                                                                                  const parsed = ownerSignupSchema.safeParse(body)
                                                                                                                                      if (!parsed.success) {
                                                                                                                                            return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 })
                                                                                                                                                }

                                                                                                                                                    const { restaurantName, ownerName, email, password, locationName, phone } = parsed.data
                                                                                                                                                        const cleanEmail = email.trim().toLowerCase()

                                                                                                                                                            // Check if user already exists
                                                                                                                                                                const existingUser = await prisma.user.findUnique({ where: { email: cleanEmail } })
                                                                                                                                                                    if (existingUser) {
                                                                                                                                                                          return NextResponse.json({ error: 'An account with this email already exists' }, { status: 409 })
                                                                                                                                                                              }

                                                                                                                                                                                  // Generate unique restaurant slug
                                                                                                                                                                                      const slug = restaurantName
                                                                                                                                                                                            .toLowerCase()
                                                                                                                                                                                                  .replace(/[^a-z0-9]+/g, '-')
                                                                                                                                                                                                        .replace(/(^-|-$)/g, '') + '-' + Math.floor(1000 + Math.random() * 9000)

                                                                                                                                                                                                            const passwordHash = await bcrypt.hash(password, 10)

                                                                                                                                                                                                                // Execute atomic tenant onboarding transaction
                                                                                                                                                                                                                    const result = await prisma.$transaction(async (tx) => {
                                                                                                                                                                                                                          // 1. Create Restaurant tenant
                                                                                                                                                                                                                                const restaurant = await tx.restaurant.create({
                                                                                                                                                                                                                                        data: {
                                                                                                                                                                                                                                                  name: restaurantName,
                                                                                                                                                                                                                                                            slug,
                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                          })

                                                                                                                                                                                                                                                                                // 2. Create primary Location
                                                                                                                                                                                                                                                                                      const location = await tx.location.create({
                                                                                                                                                                                                                                                                                              data: {
                                                                                                                                                                                                                                                                                                        restaurantId: restaurant.id,
                                                                                                                                                                                                                                                                                                                  name:         locationName,
                                                                                                                                                                                                                                                                                                                            phone:        phone ?? null,
                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                          })

                                                                                                                                                                                                                                                                                                                                                // 3. Create Owner user account
                                                                                                                                                                                                                                                                                                                                                      const user = await tx.user.create({
                                                                                                                                                                                                                                                                                                                                                              data: {
                                                                                                                                                                                                                                                                                                                                                                        restaurantId: restaurant.id,
                                                                                                                                                                                                                                                                                                                                                                                  email:        cleanEmail,
                                                                                                                                                                                                                                                                                                                                                                                            name:         ownerName,
                                                                                                                                                                                                                                                                                                                                                                                                      passwordHash,
                                                                                                                                                                                                                                                                                                                                                                                                                role:         'OWNER',
                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                              })

                                                                                                                                                                                                                                                                                                                                                                                                                                    // 4. Create Employee record for owner
                                                                                                                                                                                                                                                                                                                                                                                                                                          await tx.employee.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                  data: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            locationId: location.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      userId:     user.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                jobTitle:   'Owner & General Manager',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          phone:      phone ?? null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    isActive:   true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  })

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // 5. Seed default Menu Categories
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const appetizers = await tx.menuCategory.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      data: { restaurantId: restaurant.id, locationId: location.id, name: 'Starters & Appetizers', displayOrder: 1 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const mains = await tx.menuCategory.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          data: { restaurantId: restaurant.id, locationId: location.id, name: 'Main Courses', displayOrder: 2 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const drinks = await tx.menuCategory.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              data: { restaurantId: restaurant.id, locationId: location.id, name: 'Beverages', displayOrder: 3 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    })

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Seed sample Menu Items
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await tx.menuItem.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        data: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  categoryId: mains.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            name:       'Classic Cheeseburger',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      description: 'Angus beef patty, cheddar, lettuce, tomato, special sauce',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                price:      14.99,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          kdsStation: 'HOT',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              await tx.menuItem.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      data: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                categoryId: drinks.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          name:       'Fresh Lemonade',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    description: 'Hand-squeezed lemon juice & mint',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              price:      4.50,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        kdsStation: 'BAR',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      })

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // 6. Seed sample Floor Tables
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  await tx.table.createMany({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          data: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { locationId: location.id, name: 'Table 1', capacity: 4, posX: 1, posY: 1 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              { locationId: location.id, name: 'Table 2', capacity: 2, posX: 2, posY: 1 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { locationId: location.id, name: 'Table 3', capacity: 6, posX: 1, posY: 2 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  { locationId: location.id, name: 'Bar 1',   capacity: 1, posX: 3, posY: 1 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return { restaurant, location, user }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          })

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return NextResponse.json(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    message: 'Restaurant SaaS account created successfully with Manager, Server, and Kitchen teams.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            restaurant: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      id:   result.restaurant.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                name: result.restaurant.name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          slug: result.restaurant.slug,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          user: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    id:    result.user.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              email: result.user.email,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        role:  result.user.role,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { status: 201 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (err: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.error('Registration error:', err)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return NextResponse.json({ error: err.message || 'Internal server error during registration' }, { status: 500 })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            